<?php if ( !defined( 'ABSPATH' ) ) {
    exit;  // Exit if accessed directly.
}

$settings = array(
    'sketchbook5_setup_header'					=> array(
        'id'      => 'sketchbook5_setup_header',
        'desc'    => esc_html__( '전체 설정', 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    'wizard'               => array(
        'id'      => 'wizard',
        'name'    => esc_html__( '위저드 사용', 'x2board' ),
        'desc'    => esc_html__( '스킨 설정을 할 수 있는 내비게이션을 게시판 브라우저 좌측에 출력합니다.', 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '관리자만(기본)', 'x2board' ),
            'N'       => esc_html__( '사용 안함', 'x2board' ),
        ),
    ),
    'colorset'               => array(
        'id'      => 'colorset',
        'name'    => esc_html__( '컬러셋', 'x2board' ),
        // 'desc'    => esc_html__( 'Allow download of appended file from extenal site', 'x2board' ),
        'type'    => 'radio',
        'default' => '',
        'options' => array(
            'white'      => esc_html__( '하얀색', 'x2board' ),
            'black'       => esc_html__( '검은색', 'x2board' ),
        ),
    ),
    'default_style'               => array(
        'id'      => 'default_style',
        'name'    => esc_html__( '목록 유형', 'x2board' ),
        'type'    => 'radio',
        'default' => 'list',
        'options' => array(
            'list'      => esc_html__( '목록형', 'x2board' ),
            // 'webzine'       => esc_html__( '웹진형', 'x2board' ),
            // 'gallery'      => esc_html__( '갤러리형', 'x2board' ),
            // 'cloud_gall'       => esc_html__( '클라우드 갤러리', 'x2board' ),
            // 'guest'       => esc_html__( '방명록형', 'x2board' ),
            // 'blog'      => esc_html__( '블로그형', 'x2board' ),
            'faq'       => esc_html__( 'FAQ형', 'x2board' ),
        ),
    ),
    'link_board'               => array(
        'id'      => 'link_board',
        'name'    => esc_html__( '링크 게시판으로 사용', 'x2board' ),
        'desc'    => esc_html__( "게시판의 목록의 링크를 누르면 확장변수에서 입력한 사이트 주소로 이동합니다. 확장변수에서 'link_url' 항목을 등록하신 후 사용하세요. 'prettyphoto 애드온 사용'은 prettyphoto 애드온을 설치하고 활성화시키셔야 합니다. 자세한 사용법은 매뉴얼 또는 제작자의 홈페이지를 참조하세요.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '사용 안함(기본)', 'x2board' ),
            '2'       => esc_html__( '사용', 'x2board' ),
            '3'      => esc_html__( 'prettyPhoto 애드온 사용', 'x2board' ),
        ),
    ),
    'color'					=> array(
        'id'      => 'color',
        'name'    => esc_html__( '게시판 색상', 'x2board' ),
        'desc'    => esc_html__( "컬러셋과는 별도로 게시판의 전체 '색상' 분위기를 결정하는 부분입니다. 제목, 데코레이션, 테두리 등의 색상을 결정합니다.", 'x2board' ),
        'type'    => 'select',
        'default' => '333333',
        'options' => array(
            '333333'            => esc_html__( '검은색(기본)', 'x2board' ),
            '87cefa'        => esc_html__( '라이트스카이블루(파스텔-하늘)', 'x2board' ),
            '6495ed'            => esc_html__( '콘플라워블루(연한하늘)', 'x2board' ),
            '4169e1'            => esc_html__( '로얄블루(밝은파랑)', 'x2board' ),
            '4682b4'            => esc_html__( '스틸블루(짙은파랑)', 'x2board' ),
            'adff2f'            => esc_html__( '그린옐로우(파스텔-연두)', 'x2board' ),
            '80E12A'            => esc_html__( '초록색', 'x2board' ),
            'ffb6c1'            => esc_html__( '라이트핑크(파스텔-분홍)', 'x2board' ),
            'ff69b4'            => esc_html__( '핫핑크(분홍)', 'x2board' ),
            'ff1493'            => esc_html__( '딥핑크(선홍)', 'x2board' ),
            'ffd700'            => esc_html__( '골드(노랑)', 'x2board' ),
            'ffa500'            => esc_html__( '오렌지(주황)', 'x2board' ),
            'ff7f50'            => esc_html__( '코랄(진한주황)', 'x2board' ),
            'ff6347'            => esc_html__( '토마토(연한빨강)', 'x2board' ),
            'bc8f8f'            => esc_html__( '장미빛갈색(흑백-보라)', 'x2board' ),
            'ee82ee'            => esc_html__( '바이올렛(파스텔-보라)', 'x2board' ),
            'db7093'            => esc_html__( '팔레바이올렛레드(연한자주)', 'x2board' ),
            'c71585'            => esc_html__( '미디엄바이올렛레드(진한자주)', 'x2board' ),
        ),
    ),
    'custom_color'					=> array(
        'id'      => 'custom_color',
        'name'    => esc_html__( '게시판 색상 입력', 'x2board' ),
        'desc'    => esc_html__( "위의 색상 외에 직접 색상을 입력할 수 있습니다. 입력방법은 색태그(예 : #FFFFFF)에서 '#'을 제외한 'FFFFFF' 부분만 입력하세요. 아래의 '그림자' 색상도 반드시(!) 입력하셔야 합니다.", 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    'custom_shadow'					=> array(
        'id'      => 'custom_shadow',
        'name'    => esc_html__( '그림자 색상 입력', 'x2board' ),
        'desc'    => esc_html__( "입력방법은 색태그(예 : #FFFFFF)에서 '#'을 포함한(!) '#FFFFFF' 부분까지 입력하세요. 위의 '색상'보다 조금 더 어두운 색상을 입력하는 것을 추천합니다.", 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    'hover'					=> array(
        'id'      => 'hover',
        'name'    => esc_html__( '아이콘에 마우스 오버시 효과', 'x2board' ),
        'desc'    => esc_html__( "아이콘에 마우스 오버했을 때 효과를 설정합니다. 모바일에서는 작동하지 않습니다. *css3 animation 을 지원하는 브라우저에서만 작동합니다.", 'x2board' ),
        'type'    => 'select',
        'default' => ' ',
        'options' => array(
            ' '            => esc_html__( '회전 효과(기본)', 'x2board' ),
            'N'        => esc_html__( '사용 안함', 'x2board' ),
        ),
    ),
    'font'					=> array(
        'id'      => 'font',
        'name'    => esc_html__( '기본 글꼴 설정', 'x2board' ),
        'desc'    => esc_html__( "게시판의 기본글꼴을 설정합니다. 단, 아래의 '글꼴 선택 버튼'을 표시하는 경우 사용자가 선택한 글꼴이 우선합니다.", 'x2board' ),
        'type'    => 'select',
        'default' => ' ',
        'options' => array(
            ' '            => esc_html__( '레이아웃에 따라(기본)', 'x2board' ),
            'ng'        => esc_html__( '나눔고딕', 'x2board' ),
            'window_font'        => esc_html__( '맑은 고딕', 'x2board' ),
            'tahoma'        => esc_html__( '돋움', 'x2board' ),
        ),
    ),
    'title'					=> array(
        'id'      => 'title',
        'name'    => esc_html__( '게시판 제목', 'x2board' ),
        // 'desc'    => esc_html__( 'Notify new post and comment via comma separted list ', 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    'sub_title'					=> array(
        'id'      => 'sub_title',
        'name'    => esc_html__( '게시판 부제목', 'x2board' ),
        // 'desc'    => esc_html__( 'Notify new post and comment via comma separted list ', 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    'title_img'					=> array(
        'id'      => 'title_img',
        'name'    => esc_html__( '게시판 제목에 이미지 사용', 'x2board' ),
        'desc'    => esc_html__( "게시판 제목을 이 항목에 등록한 이미지로 사용할 수 있습니다.", 'x2board' ),
        'type'    => 'image',
        'options' => false,
    ),
    'sketchbook5_setup_header1'					=> array(
        'id'      => 'sketchbook5_setup_header1',
        'desc'    => esc_html__( '게시판 상단 설정', 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    // 'breadcrumb'               => array(
    //     'id'      => 'breadcrumb',
    //     'name'    => esc_html__( '좌측 상단 빵조각 메뉴', 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => 'Y',
    //     'options' => array(
    //         'Y'      => esc_html__( '표시(기본)', 'x2board' ),
    //         'N'       => esc_html__( '표시 안함', 'x2board' ),
    //     ),
    // ),
    'srch_window'               => array(
        'id'      => 'srch_window',
        'name'    => esc_html__( '상단 검색창', 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '버튼 표시 + 클릭 시 검색창(기본)', 'x2board' ),
            '2'       => esc_html__( '검색창 항상 표시', 'x2board' ),
            '3'       => esc_html__( '블럭형 큰 검색창(FAQ용)', 'x2board' ),
            'N'       => esc_html__( '표시 안함', 'x2board' ),
        ),
    ),
    'write_btn'               => array(
        'id'      => 'write_btn',
        'name'    => esc_html__( '쓰기 버튼', 'x2board' ),
        // 'desc'    => esc_html__( 'Allow download of appended file from extenal site', 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '표시(기본)', 'x2board' ),
            '2'       => esc_html__( '권한자에게만', 'x2board' ),
            'N'       => esc_html__( '표시 안함', 'x2board' ),
        ),
    ),
    'font_btn'               => array(
        'id'      => 'font_btn',
        'name'    => esc_html__( '글꼴 선택 버튼', 'x2board' ),
        // 'desc'    => esc_html__( 'Allow download of appended file from extenal site', 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '선택된 글꼴 표시하는 버튼(기본)', 'x2board' ),
            '2'       => esc_html__( '간단한 버튼', 'x2board' ),
            'N'       => esc_html__( '표시 안함', 'x2board' ),
        ),
    ),
    'select_lst'               => array(
        'id'      => 'select_lst',
        'name'    => esc_html__( '목록 유형 버튼', 'x2board' ),
        // 'desc'    => esc_html__( 'Allow download of appended file from extenal site', 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '표시(기본)', 'x2board' ),
            'N'       => esc_html__( '표시 안함', 'x2board' ),
        ),
    ),
    'select_lst_more'                       => array(
        'id'      => 'select_lst_more',
        'name'    => esc_html__( '목록 유형 버튼 추가', 'x2board' ),
        'type'    => 'multicheck',
        'options' => array(
            'cloud'            => esc_html__( '클라우드형', 'x2board' ),
        ),
    ),
    'cnb'               => array(
        'id'      => 'cnb',
        'name'    => esc_html__( '카테고리 메뉴 스타일', 'x2board' ),
        'desc'    => esc_html__( "'표시 안함' 게시판 설정의 '게시판 정보' 메뉴의 '분류 사용' 항목과 관계없이 표시하지 않습니다. '박스 스타일'은 2차 카테고리를 지원하지 않습니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '그라데이션 스타일(기본)', 'x2board' ),
            'cTab'      => esc_html__( '탭 스타일', 'x2board' ),
            'cnb3'      => esc_html__( '박스 스타일', 'x2board' ),
            'cnb4'      => esc_html__( '박스+테두리 스타일', 'x2board' ),
            'N'       => esc_html__( '표시 안함', 'x2board' ),
        ),
    ),
    'cnb_count'               => array(
        'id'      => 'cnb_count',
        'name'    => esc_html__( '카테고리 게시물 수 표시', 'x2board' ),
        'desc'    => esc_html__( "카테고리의 각 메뉴 이름 옆에 게시물 수를 표시합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => 'N',
        'options' => array(
            'Y'      => esc_html__( '표시', 'x2board' ),
            'N'       => esc_html__( '표시 안함(기본)', 'x2board' ),
        ),
    ),
    'cnb_open'  => array(
        'id'      => 'cnb_open',
        'name'    => esc_html__( '카테고리 처음에 펼치기', 'x2board' ),
        'desc'    => esc_html__( "'그라데이션+테두리' 스타일에서 처음부터 목록이 펼쳐져 있게 합니다.", 'x2board' ),
        'type'    => 'checkbox',
        'options' => false,
        'default' => array(	'Y' => 'Y',),
        'checked_value' => array(
            'checked' => 'Y',
            'unchecked'   => 'N',
        ),
    ),
    'cnb3_color'               => array(
        'id'      => 'cnb3_color',
        'name'    => esc_html__( '카테고리 박스 스타일 색상', 'x2board' ),
        'desc'    => esc_html__( "선택된 메뉴의 색상을 '게시판 색상'에서 선택한 색상으로 사용합니다. 기본 색상은 그레이입니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => 'N',
        'options' => array(
            'Y'      => esc_html__( '사용', 'x2board' ),
            'N'       => esc_html__( '사용 안함(기본)', 'x2board' ),
        ),
    ),
    // 'cnb3_align'               => array(
    //     'id'      => 'cnb3_align',
    //     'name'    => esc_html__( '카테고리 박스 스타일 정렬', 'x2board' ),
    //     'desc'    => esc_html__( "기본은 좌측 정렬입니다.", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => 'left',
    //     'options' => array(
    //         'left'      => esc_html__( '좌측(기본)', 'x2board' ),
    //         'center'       => esc_html__( '가운데', 'x2board' ),
    //     ),
    // ),
    'sketchbook5_setup_header2'					=> array(
        'id'      => 'sketchbook5_setup_header2',
        'desc'    => esc_html__( '게시판 하단 메뉴 설정', 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    'display_setup_button'               => array(
        'id'      => 'display_setup_button',
        'name'    => esc_html__( '표시 여부', 'x2board' ),
        // 'desc'    => esc_html__( "기본은 좌측 정렬입니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '표시(기본)', 'x2board' ),
            'N'       => esc_html__( '표시 안함', 'x2board' ),
        ),
    ),
    'srch_btm'               => array(
        'id'      => 'srch_btm',
        'name'    => esc_html__( '하단 검색창', 'x2board' ),
        // 'desc'    => esc_html__( "기본은 좌측 정렬입니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '클릭 시 표시(기본)', 'x2board' ),
            '2'      => esc_html__( '처음부터 표시', 'x2board' ),
            'N'       => esc_html__( '표시 안함', 'x2board' ),
        ),
    ),
    'write_btm_btn'               => array(
        'id'      => 'write_btm_btn',
        'name'    => esc_html__( '쓰기 버튼', 'x2board' ),
        // 'desc'    => esc_html__( "기본은 좌측 정렬입니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '표시(기본)', 'x2board' ),
            '2'      => esc_html__( '권한자에게만', 'x2board' ),
            'N'       => esc_html__( '표시 안함', 'x2board' ),
        ),
    ),
    'btm_mn'                       => array(
        'id'      => 'btm_mn',
        'name'    => esc_html__( '버튼 추가', 'x2board' ),
        // 'desc'    => esc_html__( 'Available post status', 'x2board' ),
        'type'    => 'multicheck',
        'options' => array(
            'home'            => esc_html__( '목록 버튼 표시', 'x2board' ),
            'tag'            => esc_html__( 'TAG 버튼 표시', 'x2board' ),
        ),
        // 'mandatory' => array(
        //     'PUBLIC'            => 'mandatory',
        // ),
    ),
    'sketchbook5_setup_header3'					=> array(
        'id'      => 'sketchbook5_setup_header3',
        'desc'    => esc_html__( '목록 공통 설정', 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    'rd_lst'               => array(
        'id'      => 'rd_lst',
        'name'    => esc_html__( '본문에서 목록 출력', 'x2board' ),
        'desc'    => esc_html__( "본문을 볼 때 본문 하단에 목록을 출력할 것인지를 결정합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => 'Y',
        'options' => array(
            'Y'      => esc_html__( '출력(기본)', 'x2board' ),
            'N'       => esc_html__( '표시 안함', 'x2board' ),
        ),
    ),
    // 'notice_style'               => array(
    //     'id'      => 'notice_style',
    //     'name'    => esc_html__( '공지 출력 형식', 'x2board' ),
    //     'desc'    => esc_html__( "공지의 출력형식을 결정합니다. 모든 목록형태에서 동일한 공지의 출력이 필요한 경우 사용됩니다.", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '선택된 목록 유형과 같은 방식(기본)', 'x2board' ),
    //         '2'       => esc_html__( '모든 목록 유형에서 동일한 한 줄 공지 형식', 'x2board' ),
    //     ),
    // ),
    'subject_cut_size'					=> array(
        'id'      => 'subject_cut_size',
        'name'    => esc_html__( '제목 글자 수', 'x2board' ),
        'desc'    => esc_html__( '입력하지 않으면 기본 설정은 설정은 자르지 않습니다. *갤러리형은 별도 항목이 존재합니다.', 'x2board' ),
        'type'    => 'number',
        'options' => false,
    ),
    'content_cut_size'					=> array(
        'id'      => 'content_cut_size',
        'name'    => esc_html__( '내용 글자 수', 'x2board' ),
        'desc'    => esc_html__( '입력하지 않으면 기본 설정은 240 입니다.', 'x2board' ),
        'type'    => 'number',
        'options' => false,
    ),
    'duration_new'					=> array(
        'id'      => 'duration_new',
        'name'    => esc_html__( '새 글 표시 시간', 'x2board' ),
        'desc'    => esc_html__( '입력하지 않으면 기본 설정은 24 입니다.', 'x2board' ),
        'type'    => 'number',
        'options' => false,
    ),
    'display_ip_address'  => array(
        'id'      => 'display_ip_address',
        'name'    => esc_html__( '아이피 주소 표시', 'x2board' ),
        // 'desc'    => esc_html__( "'그라데이션+테두리' 스타일에서 처음부터 목록이 펼쳐져 있게 합니다.", 'x2board' ),
        'type'    => 'checkbox',
        'options' => false,
        'default' => array(	'N' => 'N',),
        'checked_value' => array(
            'checked' => 'Y',
            'unchecked'   => 'N',
        ),
    ),
    'no_img'					=> array(
        'id'      => 'no_img',
        'name'    => esc_html__( '대체 이미지', 'x2board' ),
        'desc'    => esc_html__( "목록과 본문에서 섬네일 또는 프로필 이미지가 없는 경우 '?' 혹은 'No Image' 표시 대신 사용자가 직접 등록한 이미지를 사용할 수 있습니다. 여기에 이미지를 등록하면 활성화됩니다.", 'x2board' ),
        'type'    => 'image',
        'options' => false,
    ),
    'hd_tx'               => array(
        'id'      => 'hd_tx',
        'name'    => esc_html__( "'상단 내용' 출력 방식", 'x2board' ),
        'desc'    => esc_html__( "게시판 제목이나 공지 등에 활용되는 게시판 설정의 '게시판 정보'  항목의 '상단 내용'을 본문 출력 방식을 설정합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '항상 출력(기본)', 'x2board' ),
            '2'       => esc_html__( '본문에서만 출력', 'x2board' ),
            '3'       => esc_html__( '본문에서 출력 안함', 'x2board' ),
        ),
    ),
    'bubble'               => array(
        'id'      => 'bubble',
        'name'    => esc_html__( "말풍선 기능", 'x2board' ),
        'desc'    => esc_html__( "해당 요소의 'title'을 가지고 말풍선(툴팁)을 만들어 시인성을 높입니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '사용(기본)', 'x2board' ),
            'N'       => esc_html__( '사용 안함', 'x2board' ),
        ),
    ),
    'fdb_count'               => array(
        'id'      => 'fdb_count',
        'name'    => esc_html__( "댓글수 스타일", 'x2board' ),
        'desc'    => esc_html__( "'목록형', '갤러리형'에서 댓글수의 디자인을 결정합니다. 박스형(강조형)은 댓글 수를 강조할 때 유용합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '텍스트형(기본)', 'x2board' ),
            'fdb_count'       => esc_html__( '박스형(강조형) - 좌측 정렬', 'x2board' ),
            'fdb_count2'       => esc_html__( '박스형(강조형) - 우측 정렬', 'x2board' ),
        ),
    ),
    'sketchbook5_setup_header4'					=> array(
        'id'      => 'sketchbook5_setup_header4',
        'desc'    => esc_html__( '목록형 설정', 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    'show_cate'               => array(
        'id'      => 'show_cate',
        'name'    => esc_html__( "카테고리 표시", 'x2board' ),
        'desc'    => esc_html__( "목록에서 제목 앞에 카테고리를 표시합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '표시(기본)', 'x2board' ),
            'N'       => esc_html__( '표시 안함', 'x2board' ),
        ),
    ),
    'normal_lst_tdW'					=> array(
        'id'      => 'normal_lst_tdW',
        'name'    => esc_html__( '분류, 닉네임 영역 넓이 제한', 'x2board' ),
        'desc'    => esc_html__( "분류, 닉네임 영역이 길어지는 경우 제목 영역이 너무 좁아지는 것을 막기 위해 최대 넓이를 제한합니다. 입력하지 않으면 '90'(px)입니다.", 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    'preview'  => array(
        'id'      => 'preview',
        'name'    => esc_html__( '요약(내용), 섬네일 미리보기', 'x2board' ),
        'desc'    => esc_html__( "*미리보기의 이미지의 크기는 '갤러리형' 섬네일 설정에 따릅니다.", 'x2board' ),
        'type'    => 'multicheck',
        'options' => array(
            'tx'            => esc_html__( '요약', 'x2board' ),
            'img'            => esc_html__( '섬네일', 'x2board' ),
        ),
        // 'mandatory' => array(
        //     'PUBLIC'            => 'mandatory',
        // ),
    ),
    'preview_tx'					=> array(
        'id'      => 'preview_tx',
        'name'    => esc_html__( '미리보기 요약 글자 수', 'x2board' ),
        'desc'    => esc_html__( "입력하지 않으면 '150'입니다.", 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    'list_m'               => array(
        'id'      => 'list_m',
        'name'    => esc_html__( "*모바일형 설정", 'x2board' ),
        'desc'    => esc_html__( "모바일에서 웹용 테이블 목록을 사용할 것인지 모바일에 최적화된 목록을 사용할 것인지를 결정합니다. 몇가지 옵션항목은 웹진형과 공유합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '모바일형 사용(기본)', 'x2board' ),
            '2'       => esc_html__( '테이블형 사용', 'x2board' ),
        ),
    ),
    'list_m_tmb'               => array(
        'id'      => 'list_m_tmb',
        'name'    => esc_html__( "*모바일형 썸네일", 'x2board' ),
        'desc'    => esc_html__( "모바일형에서 썸네일의 표시 여부를 결정합니다. 썸네일 크기는 웹진형의 설정을 사용합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '표시 안함(기본)', 'x2board' ),
            'Y'       => esc_html__( '표시', 'x2board' ),
        ),
    ),
    'sketchbook5_setup_header5'					=> array(
        'id'      => 'sketchbook5_setup_header5',
        'desc'    => esc_html__( '웹진형, 갤러리형, 모바일(목록)형 공통 설정', 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    'tmb_effect'               => array(
        'id'      => 'tmb_effect',
        'name'    => esc_html__( "섬네일 인트로 효과", 'x2board' ),
        'desc'    => esc_html__( "페이지 로딩 시에 섬네일 효과를 설정합니다. (단지 디자인 요소만이 아닌, 이미지가 로딩되기 전에 이미지 영역을 감싸는 요소들이 흐트러지는 것을 방지하는 역할을 합니다.)", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( 'Fade-In(기본)', 'x2board' ),
            '2'       => esc_html__( "'loading' 아이콘 + Fade-In", 'x2board' ),
            'N'       => esc_html__( "없음", 'x2board' ),
        ),
    ),
    'ext_img'  => array(
        'id'      => 'ext_img',
        'name'    => esc_html__( '새 글 등 아이콘 표시', 'x2board' ),
        // 'desc'    => esc_html__( "*미리보기의 이미지의 크기는 '갤러리형' 섬네일 설정에 따릅니다.", 'x2board' ),
        'type'    => 'multicheck',
        'options' => array(
            // 'zine'            => esc_html__( '웹진형', 'x2board' ),
            // 'gall'            => esc_html__( '갤러리형', 'x2board' ),
            'list_m'            => esc_html__( '모바일(목록)형', 'x2board' ),
        ),
        // 'mandatory' => array(
        //     'PUBLIC'            => 'mandatory',
        // ),
    ),
    'cmt_count'  => array(
        'id'      => 'cmt_count',
        'name'    => esc_html__( '댓글수 표시', 'x2board' ),
        // 'desc'    => esc_html__( "*미리보기의 이미지의 크기는 '갤러리형' 섬네일 설정에 따릅니다.", 'x2board' ),
        'type'    => 'multicheck',
        'options' => array(
            // 'zine'            => esc_html__( '웹진형', 'x2board' ),
            // 'gall'            => esc_html__( '갤러리형', 'x2board' ),
            'list_m'            => esc_html__( '모바일(목록)형', 'x2board' ),
        ),
        // 'mandatory' => array(
        //     'PUBLIC'            => 'mandatory',
        // ),
    ),
    'ribbon_style'               => array(
        'id'      => 'ribbon_style',
        'name'    => esc_html__( "리본 스타일", 'x2board' ),
        // 'desc'    => esc_html__( "페이지 로딩 시에 섬네일 효과를 설정합니다. (단지 디자인 요소만이 아닌, 이미지가 로딩되기 전에 이미지 영역을 감싸는 요소들이 흐트러지는 것을 방지하는 역할을 합니다.)", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '삼각 리본(기본)', 'x2board' ),
            '2'       => esc_html__( "타일형(사각) 리본", 'x2board' ),
        ),
    ),
    'ribbon_img'					=> array(
        'id'      => 'ribbon_img',
        'name'    => esc_html__( '리본 이미지', 'x2board' ),
        'desc'    => esc_html__( "위의 '리본 스타일' 항목에서 '삼각 리본'을 선택하시는 경우 리본 이미지를 등록하여 사용할 수 있습니다(*공지, 새 글, 업데이트 제외). 입력하지 않으면 60 X 60(px)이 기본사이즈입니다. 직접 등록하시는 경우 등록하시는 이미지의 사이즈(가로, 세로 동일)를 입력해주세요.", 'x2board' ),
        'type'    => 'image',
        'options' => false,
    ),
    'ribbon_size'					=> array(
        'id'      => 'ribbon_size',
        'name'    => esc_html__( '리본 이미지 사이즈', 'x2board' ),
        'desc'    => esc_html__( "'숫자'만(px 단위입니다) 입력해주세요.", 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    'ribbon_align'               => array(
        'id'      => 'ribbon_align',
        'name'    => esc_html__( "타일형 리본 정렬", 'x2board' ),
        // 'desc'    => esc_html__( "페이지 로딩 시에 섬네일 효과를 설정합니다. (단지 디자인 요소만이 아닌, 이미지가 로딩되기 전에 이미지 영역을 감싸는 요소들이 흐트러지는 것을 방지하는 역할을 합니다.)", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '우측 상단(기본)', 'x2board' ),
            'left'       => esc_html__( "좌측 상단", 'x2board' ),
        ),
    ),
    'ribbon_color'					=> array(
        'id'      => 'ribbon_color',
        'name'    => esc_html__( '타일형 리본 색상', 'x2board' ),
        'desc'    => esc_html__( "타일형 리본을 선택한 경우 색상을 직접 지정할 수 있습니다(*공지, 새 글, 업데이트 제외). 입력방법은 풀코드를 입력해야합니다. 예) #FF0, rgb(0,25,55), rgba(55,15,5,1) 등", 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    'extra_num'					=> array(
        'id'      => 'extra_num',
        'name'    => esc_html__( '리본 확장변수 번호', 'x2board' ),
        'desc'    => esc_html__( "'좌측 상단 리본'에서 확장변수 사용 시 선택할 확장변수의 번호를 설정합니다. 설정이 없으면 1번이 지정됩니다.", 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    'sketchbook5_setup_header6'					=> array(
        'id'      => 'sketchbook5_setup_header6',
        'desc'    => esc_html__( "웹진형 설정 (*표시 : '모바일(목록)형'과 공통)", 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    // 'zine_style'               => array(
    //     'id'      => 'zine_style',
    //     'name'    => esc_html__( "웹진 스타일", 'x2board' ),
    //     // 'desc'    => esc_html__( "페이지 로딩 시에 섬네일 효과를 설정합니다. (단지 디자인 요소만이 아닌, 이미지가 로딩되기 전에 이미지 영역을 감싸는 요소들이 흐트러지는 것을 방지하는 역할을 합니다.)", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '목록 스타일(기본)', 'x2board' ),
    //         '2'       => esc_html__( "목록 스타일2(큰 날짜)", 'x2board' ),
    //         '3'       => esc_html__( "카드 스타일(테두리 있음)", 'x2board' ),
    //         '4'       => esc_html__( "카드 스타일2(테두리 없음)", 'x2board' ),
    //     ),
    // ),
    // 'card_effect'               => array(
    //     'id'      => 'card_effect',
    //     'name'    => esc_html__( "카드 스타일 효과", 'x2board' ),
    //     // 'desc'    => esc_html__( "페이지 로딩 시에 섬네일 효과를 설정합니다. (단지 디자인 요소만이 아닌, 이미지가 로딩되기 전에 이미지 영역을 감싸는 요소들이 흐트러지는 것을 방지하는 역할을 합니다.)", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '부드러운 이동(기본)', 'x2board' ),
    //         'N'       => esc_html__( "효과 없음", 'x2board' ),
    //     ),
    // ),
    'zine_margin'					=> array(
        'id'      => 'zine_margin',
        'name'    => esc_html__( '카드 스타일 여백', 'x2board' ),
        'desc'    => esc_html__( "'카드 스타일'에서 바깥 여백(margin)을 설정합니다. 입력하지 않으면 기본 설정은 '10' 입니다.", 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    'zine_hover'               => array(
        'id'      => 'zine_hover',
        'name'    => esc_html__( "마우스 오버 전환 효과", 'x2board' ),
        'desc'    => esc_html__( "마우스 오버시에 섬네일이 기울어지거나, 확대되는 효과를 사용하지 않습니다. *테두리 효과에는 영향을 미치지 않습니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '사용(기본값)', 'x2board' ),
            'N'       => esc_html__( "사용 안함", 'x2board' ),
        ),
    ),
    'zine_thumb_type'               => array(
        'id'      => 'zine_thumb_type',
        'name'    => esc_html__( "섬네일 비율(*)", 'x2board' ),
        // 'desc'    => esc_html__( "마우스 오버시에 섬네일이 기울어지거나, 확대되는 효과를 사용하지 않습니다. *테두리 효과에는 영향을 미치지 않습니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '크롭(기본)', 'x2board' ),
            'ratio'       => esc_html__( "원본 비율", 'x2board' ),
        ),
    ),
    'zine_thumb_width'					=> array(
        'id'      => 'zine_thumb_width',
        'name'    => esc_html__( '섬네일 넓이', 'x2board' ),
        'desc'    => esc_html__( "섬네일의 넓이에 따라 '카드스타일'에서 카드 블록의 넓이가 결정됩니다. 입력하지 않으면 기본 설정은 '90' 입니다.", 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    'zine_thumb_height'					=> array(
        'id'      => 'zine_thumb_height',
        'name'    => esc_html__( '섬네일 높이', 'x2board' ),
        'desc'    => esc_html__( "입력하지 않으면 기본 설정은 '90' 입니다.", 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    // 'zine_css'     => array(
    //     'id'      => 'zine_css',
    //     'name'    => esc_html__( '섬네일 css', 'x2board' ),
    //     'desc'    => esc_html__( '섬네일의 css를 직접 입력할 수 있습니다. 커스텀 사용자를 위한 항목입니다.', 'x2board' ),
    //     'type'    => 'textarea',
    //     'options' => false,
    // ),
    // 'zine_ribbon'					=> array(
    //     'id'      => 'zine_ribbon',
    //     'name'    => esc_html__( '섬네일 리본', 'x2board' ),
    //     'desc'    => esc_html__( "섬네일 좌측 상단의 리본에 들어갈 변수를 출력합니다. 확장변수의 경우 위의 '웹진, 갤러리 공통메뉴'에서 번호를 설정하세요. 설정이 없으면 1번을 출력합니다.", 'x2board' ),
    //     'type'    => 'select',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '            => esc_html__( '새 글 > 업데이트(기본)', 'x2board' ),
    //         'N'        => esc_html__( '출력 안함', 'x2board' ),
    //         'new_date'            => esc_html__( '새 글 > 업데이트 > 날짜', 'x2board' ),
    //         'cate'        => esc_html__( '카테고리', 'x2board' ),
    //         'date'            => esc_html__( '날짜', 'x2board' ),
    //         'read'        => esc_html__( '읽은 수', 'x2board' ),
    //         'vote'            => esc_html__( '추천 수', 'x2board' ),
    //         'cmt'        => esc_html__( '댓글 수', 'x2board' ),
    //         'extra'            => esc_html__( '확장변수', 'x2board' ),
    //     ),
    // ),
    'zine_extra'               => array(
        'id'      => 'zine_extra',
        'name'    => esc_html__( "확장변수 출력(*)", 'x2board' ),
        'desc'    => esc_html__( "하단에 메타 정보 영역에 확장변수의 목록을 출력합니다. *모바일형과 설정을 공유합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            'Y'      => esc_html__( '출력', 'x2board' ),
            ' '       => esc_html__( "출력 안함(기본)", 'x2board' ),
        ),
    ),
    'zine_tx_color'               => array(
        'id'      => 'zine_tx_color',
        'name'    => esc_html__( "메타 정보 색상(*)", 'x2board' ),
        'desc'    => esc_html__( "하단의 글쓴이, 조회수 등의 메타 정보의 글자 색상을 설정합니다. *모바일형과 설정을 공유합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '게시판 색상에 따라(기본)', 'x2board' ),
            'N'       => esc_html__( "흑백톤", 'x2board' ),
        ),
    ),
    'zine_info_icon'               => array(
        'id'      => 'zine_info_icon',
        'name'    => esc_html__( "메타 정보 아이콘(*)", 'x2board' ),
        'desc'    => esc_html__( "메타 정보에 아이콘을 사용합니다. *모바일형과 설정을 공유합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '표시 안함(기본)', 'x2board' ),
            'info_icon'       => esc_html__( "아이콘만 표시", 'x2board' ),
            'info_icon2'       => esc_html__( "아이콘+텍스트 표시", 'x2board' ),
        ),
    ),
    'sketchbook5_setup_header7'					=> array(
        'id'      => 'sketchbook5_setup_header7',
        'desc'    => esc_html__( "갤러리 형 (*표시 : '클라우드 갤러리'와 공통)", 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    // 'gall_style'               => array(
    //     'id'      => 'gall_style',
    //     'name'    => esc_html__( "갤러리 스타일", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '이미지 아래 제목 표시(기본)', 'x2board' ),
    //         '2'       => esc_html__( "액자 스타일(전체 테두리)", 'x2board' ),
    //     ),
    // ),
    // 'gall_align'               => array(
    //     'id'      => 'gall_align',
    //     'name'    => esc_html__( "섬네일 정렬", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '가운데 정렬(기본값)', 'x2board' ),
    //         'left'       => esc_html__( "좌측 정렬", 'x2board' ),
    //     ),
    // ),
    'thumbnail_type'               => array(
        'id'      => 'thumbnail_type',
        'name'    => esc_html__( "섬네일 비율(*)", 'x2board' ),
        'type'    => 'radio',
        'default' => 'crop',
        'options' => array(
            'crop'      => esc_html__( '크롭(기본)', 'x2board' ),
            'ratio'       => esc_html__( "원본 비율", 'x2board' ),
        ),
    ),
    'thumbnail_width'					=> array(
        'id'      => 'thumbnail_width',
        'name'    => esc_html__( '섬네일 넓이(*)', 'x2board' ),
        'desc'    => esc_html__( "'갤러리형' 및 '클라우드 갤러리형'의 섬네일에 적용됩니다. 입력하지 않으면 기본 설정은 '90' 입니다.", 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    'thumbnail_height'					=> array(
        'id'      => 'thumbnail_height',
        'name'    => esc_html__( '섬네일 높이(*)', 'x2board' ),
        'desc'    => esc_html__( "'갤러리형' 및 '클라우드 갤러리형'의 섬네일에 적용됩니다. 입력하지 않으면 기본 설정은 '90' 입니다.", 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    // 'gallery_tl'               => array(
    //     'id'      => 'gallery_tl',
    //     'name'    => esc_html__( "제목 표시(*)", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '표시(기본)', 'x2board' ),
    //         'N'       => esc_html__( "표시 안함", 'x2board' ),
    //     ),
    // ),
    // 'gall_tl_cut'					=> array(
    //     'id'      => 'gall_tl_cut',
    //     'name'    => esc_html__( '갤러리형 제목 글자 수(*)', 'x2board' ),
    //     'desc'    => esc_html__( "입력하지 않으면 기본 설정은 설정은 자르지 않습니다.", 'x2board' ),
    //     'type'    => 'text',
    //     'options' => false,
    // ),
    // 'gall_tl_font'               => array(
    //     'id'      => 'gall_tl_font',
    //     'name'    => esc_html__( "액자스타일 제목 글꼴", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '필기체(기본)', 'x2board' ),
    //         'ng'       => esc_html__( "글꼴 설정에 따라", 'x2board' ),
    //     ),
    // ),
    // 'li_width'					=> array(
    //     'id'      => 'li_width',
    //     'name'    => esc_html__( '섬네일 영역 넓이', 'x2board' ),
    //     'desc'    => esc_html__( "이 항목을 전체 영역에 맞게 설정하여 '가로 정렬할 이미지의 수'를 설정합니다. 예) 게시판 전체영역의 넓이가 '800px'이고 가로 갯수를 '4'개로 하고 싶은 경우 설정 넓이는 '200'으로 설정하시면 됩니다. 입력하지 않으면 섬네일 넓이에 +40 입니다.", 'x2board' ),
    //     'type'    => 'text',
    //     'options' => false,
    // ),
    // 'li_height'					=> array(
    //     'id'      => 'li_height',
    //     'name'    => esc_html__( '섬네일 영역 높이', 'x2board' ),
    //     'desc'    => esc_html__( "입력하지 않으면 섬네일 높이에 +80 입니다.", 'x2board' ),
    //     'type'    => 'text',
    //     'options' => false,
    // ),
    // 'gall_shadow'               => array(
    //     'id'      => 'gall_shadow',
    //     'name'    => esc_html__( "섬네일 그림자", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '표시(기본)', 'x2board' ),
    //         'N'       => esc_html__( "표시 안함", 'x2board' ),
    //     ),
    // ),
    // 'thumb_css'     => array(
    //     'id'      => 'thumb_css',
    //     'name'    => esc_html__( '섬네일 css', 'x2board' ),
    //     'desc'    => esc_html__( '섬네일의 css를 직접 입력할 수 있습니다. 커스텀 사용자를 위한 항목입니다.', 'x2board' ),
    //     'type'    => 'textarea',
    //     'options' => false,
    // ),
    // 'tmb_hover'               => array(
    //     'id'      => 'tmb_hover',
    //     'name'    => esc_html__( "섬네일 마우스 오버 효과", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( 'Fade-In(기본)', 'x2board' ),
    //         '2'       => esc_html__( "위에서 닦아내기", 'x2board' ),
    //         '3'       => esc_html__( "옆에서 닦아내기", 'x2board' ),
    //         '4'       => esc_html__( "우측 하단으로 닦아내기", 'x2board' ),
    //         'R'       => esc_html__( "랜덤효과", 'x2board' ),
    //         'N'       => esc_html__( "없음", 'x2board' ),
    //     ),
    // ),
    // 'tmb_hover_bg'               => array(
    //     'id'      => 'tmb_hover_bg',
    //     'name'    => esc_html__( "섬네일 마우스 오버 배경색", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '검은색+투명(기본)', 'x2board' ),
    //         '2'       => esc_html__( "'게시판 효과 색상'", 'x2board' ),
    //         '3'       => esc_html__( "'게시판 효과 색상'+투명", 'x2board' ),
    //     ),
    // ),
    // 'gall_ribbon'					=> array(
    //     'id'      => 'gall_ribbon',
    //     'name'    => esc_html__( '좌측 상단 리본', 'x2board' ),
    //     'desc'    => esc_html__( "섬네일 좌측 상단의 리본에 들어갈 변수를 출력합니다. 확장변수의 경우 위의 '웹진, 갤러리 공통메뉴'에서 번호를 설정하세요. 설정이 없으면 1번을 출력합니다.", 'x2board' ),
    //     'type'    => 'select',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '            => esc_html__( '새 글 > 업데이트 > 날짜(기본)', 'x2board' ),
    //         'N'        => esc_html__( '표시 안함', 'x2board' ),
    //         'date'            => esc_html__( '날짜', 'x2board' ),
    //         'new_update'        => esc_html__( '새 글 > 업데이트', 'x2board' ),
    //         'cate'            => esc_html__( '카테고리', 'x2board' ),
    //         'read'        => esc_html__( '읽은 수', 'x2board' ),
    //         'vote'            => esc_html__( '추천 수', 'x2board' ),
    //         'cmt'        => esc_html__( '댓글 수', 'x2board' ),
    //         'extra'            => esc_html__( '확장변수1', 'x2board' ),
    //     ),
    // ),
    // 'trans_window'					=> array(
    //     'id'      => 'trans_window',
    //     'name'    => esc_html__( '우측 하단 투명창', 'x2board' ),
    //     'desc'    => esc_html__( "섬네일 우측 하단에 들어갈 변수를 출력합니다. 확장변수의 경우 아래에서 출력할 확장변수 번호를 설정하세요. 설정이 없으면 1번을 출력합니다.", 'x2board' ),
    //     'type'    => 'select',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '            => esc_html__( '글쓴이(기본)', 'x2board' ),
    //         'N'        => esc_html__( '표시 안함', 'x2board' ),
    //         'date'            => esc_html__( '날짜', 'x2board' ),
    //         'cate'            => esc_html__( '카테고리', 'x2board' ),
    //         'read'        => esc_html__( '읽은 수', 'x2board' ),
    //         'vote'            => esc_html__( '추천 수', 'x2board' ),
    //         'cmt'        => esc_html__( '댓글 수', 'x2board' ),
    //         'extra'            => esc_html__( '확장변수2', 'x2board' ),
    //     ),
    // ),
    'extra_num2'					=> array(
        'id'      => 'extra_num2',
        'name'    => esc_html__( '투명창 확장변수 번호', 'x2board' ),
        'desc'    => esc_html__( "'우측 하단 투명창'에서 확장변수 사용 시 선택할 확장변수의 번호를 설정합니다. 설정이 없으면 1번이 지정됩니다,", 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    // 'deco'               => array(
    //     'id'      => 'deco',
    //     'name'    => esc_html__( "데코레이션", 'x2board' ),
    //     'desc'    => esc_html__( "섬네일을 꾸밉니다.", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '책갈피 스타일(기본)', 'x2board' ),
    //         '2'       => esc_html__( "테이프 스타일", 'x2board' ),
    //         'N'       => esc_html__( "표시 안함", 'x2board' ),
    //     ),
    // ),
    'deco_img'					=> array(
        'id'      => 'deco_img',
        'name'    => esc_html__( '데코레이션 이미지', 'x2board' ),
        'desc'    => esc_html__( "기본 제공되는 데코레이션 이미지 외에 사용자가 직접 이미지를 등록할 수 있습니다. 상단 가운데에 위치하게 됩니다.", 'x2board' ),
        'type'    => 'image',
        'options' => false,
    ),
    // 'gall_deg'					=> array(
    //     'id'      => 'gall_deg',
    //     'name'    => esc_html__( '섬네일의 기울기', 'x2board' ),
    //     'desc'    => esc_html__( "섬네일의 기울기를 사용합니다. 숫자(양수)를 입력하여 범위를 설정합니다. 단위는 각도(0~180)로 입니다. 입력하지 않으면 사용하지 않습니다. *css3를 지원하는 브라우저에서만 적용됩니다.", 'x2board' ),
    //     'type'    => 'text',
    //     'options' => false,
    // ),
    // // <var name="gall_hover_img" type="image">
    // //     <title xml:lang="ko">마우스 오버 이미지</title>
    // //     <description xml:lang="ko">마우스 오버했을 때의 이미지를 사용자가 직접 이미지를 등록할 수 있습니다. 가운데에 위치하게 됩니다.</description>
    // // </var>
    'sketchbook5_setup_header8'					=> array(
        'id'      => 'sketchbook5_setup_header8',
        'desc'    => esc_html__( "클라우드 갤러리", 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    // 'cloud_rand'               => array(
    //     'id'      => 'cloud_rand',
    //     'name'    => esc_html__( "섬네일의 무작위 위치", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '처음부터(기본)', 'x2board' ),
    //         'N'       => esc_html__( "적용 안함", 'x2board' ),
    //     ),
    // ),
    // 'cloud_y'					=> array(
    //     'id'      => 'cloud_y',
    //     'name'    => esc_html__( '갤러리 높이', 'x2board' ),
    //     'desc'    => esc_html__( "갤러리의 높이(=섬네일의 무작위 세로 위치의 범위)를 설정합니다. 설정하지 않으면 기본 '600' 입니다.", 'x2board' ),
    //     'type'    => 'text',
    //     'options' => false,
    // ),
    // 'cloud_rotate'               => array(
    //     'id'      => 'cloud_rotate',
    //     'name'    => esc_html__( "섬네일 기울기", 'x2board' ),
    //     'desc'    => esc_html__( "*css3를 지원하는 브라우저에서만 적용됩니다.", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '처음부터(기본)', 'x2board' ),
    //         'N'       => esc_html__( "적용 안함", 'x2board' ),
    //     ),
    // ),
    // 'cloud_deg'					=> array(
    //     'id'      => 'cloud_deg',
    //     'name'    => esc_html__( '섬네일 기울기 범위', 'x2board' ),
    //     'desc'    => esc_html__( "섬네일의 기울기 좌우 범위를 설정합니다. 단위는 각도(0~180)로 '숫자(양수)'만 입력하세요. 설정하지 않으면 기본 '25' 입니다.", 'x2board' ),
    //     'type'    => 'text',
    //     'options' => false,
    // ),
    // 'cloud_btn'               => array(
    //     'id'      => 'cloud_btn',
    //     'name'    => esc_html__( "무작위, 기울기, 재위치 버튼", 'x2board' ),
    //     'desc'    => esc_html__( "이 버튼들을 표시하면 관리자가 설정한 무작위 위치, 기울기의 최초 설정보다 사용자의 해당 버튼 활성화 여부가 우선합니다.", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '표시(기본)', 'x2board' ),
    //         'N'       => esc_html__( "표시 안함", 'x2board' ),
    //     ),
    // ),
    // 'cloud_margin'					=> array(
    //     'id'      => 'cloud_margin',
    //     'name'    => esc_html__( '섬네일의 여백', 'x2board' ),
    //     'desc'    => esc_html__( "'무작위 위치'를 사용하지 않을 경우의 정렬된 이미지의 여백을 설정합니다. 설정하지 않으면 기본 '12' 입니다.", 'x2board' ),
    //     'type'    => 'text',
    //     'options' => false,
    // ),
    'sketchbook5_setup_header9'					=> array(
        'id'      => 'sketchbook5_setup_header9',
        'desc'    => esc_html__( "FAQ 게시판 형", 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    // 'faq_style'               => array(
    //     'id'      => 'faq_style',
    //     'name'    => esc_html__( "스타일 프리셋", 'x2board' ),
    //     'desc'    => esc_html__( "FAQ 게시판의 스타일을 설정합니다. '공식 FAQ모듈 스타일'은 공식 FAQ모듈과 유사한 스타일로 변형시킵니다.", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '기본값(기본)', 'x2board' ),
    //         'faq_official'       => esc_html__( "공식 FAQ모듈 스타일", 'x2board' ),
    //     ),
    // ),
    'sketchbook5_setup_header10'					=> array(
        'id'      => 'sketchbook5_setup_header10',
        'desc'    => esc_html__( "블로그 형", 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    // 'blog_style'               => array(
    //     'id'      => 'blog_style',
    //     'name'    => esc_html__( "스타일 프리셋", 'x2board' ),
    //     'desc'    => esc_html__( "블로그형 스타일을 설정합니다. 외곽 영역에서 테두리와 그림자 여부를 설정합니다. *익스8 이하의 경우 'css3pie 애드온'을 활성화하여야 적용이 됩니다.", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '테두리+그림자(기본)', 'x2board' ),
    //         'no_style'       => esc_html__( "없음", 'x2board' ),
    //     ),
    // ),
    'sketchbook5_setup_header11'					=> array(
        'id'      => 'sketchbook5_setup_header11',
        'desc'    => esc_html__( "글쓰기 및 댓글쓰기 설정", 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    'tl_color'               => array(
        'id'      => 'tl_color',
        'name'    => esc_html__( "'제목 색깔' 및 '제목 굵기' 표시", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '관리자만(기본)', 'x2board' ),
            '2'       => esc_html__( "모든 사용자", 'x2board' ),
        ),
    ),
    /*'wrt_opt'                       => array(
        'id'      => 'wrt_opt',
        'name'    => esc_html__( '쓰기 옵션 기본값 설정', 'x2board' ),
        'type'    => 'multicheck',
        'options' => array(
            'notify'            => esc_html__( '알림 기본 체크', 'x2board' ),
            'secret'            => esc_html__( '비밀글 기본 체크', 'x2board' ),
        ),
        // 'mandatory' => array(
        //     'PUBLIC'            => 'mandatory',
        // ),
    ),*/
    // 'content_default'     => array(
    //     'id'      => 'content_default',
    //     'name'    => esc_html__( '글 작성시 미리 입력된 글 출력', 'x2board' ),
    //     'desc'    => esc_html__( '글쓰기 화면에서 글쓰기 창 안에 표시될 글을 출력하는 기능입니다. 미리 준비된 양식이나 글쓰기 안내글 등에 사용할 수 있습니다. HTML을 사용 할 수 있습니다.', 'x2board' ),
    //     'type'    => 'textarea',
    //     'options' => false,
    // ),
    'cmt_wrt'               => array(
        'id'      => 'cmt_wrt',
        'name'    => esc_html__( "댓글 에디터 설정", 'x2board' ),
        'desc'    => esc_html__( "(1) Textarea : 에디터를 불러오지 않고 글을 쓸 수 있습니다. (2) 에디터  (3) SocialXE : '난다날아'님의 'SocialXE' 와 본 스킨 제작자가 배포한 'SketchBook5 SocialXE 댓글 위젯 스킨'이 모두 설치되어 있는 경우에만 작동하는 옵션입니다.(※ 반드시 이 의미가 무엇인지 아는 사용자만 설정하시길 바랍니다.)", 'x2board' ),
        'type'    => 'radio',
        'default' => 'simple',
        'options' => array(
            'simple'      => esc_html__( 'Textarea(기본)', 'x2board' ),
            'editor'       => esc_html__( "에디터", 'x2board' ),
            'sns'       => esc_html__( "SocialXE", 'x2board' ),
        ),
    ),
    'select_editor'               => array(
        'id'      => 'select_editor',
        'name'    => esc_html__( "에디터 선택 버튼 표시", 'x2board' ),
        'desc'    => esc_html__( "본문의 댓글 영역에 사용자가 에디터를 선택할 수 있는 버튼을 표시합니다. 위의 '댓글 에디터 설정'에서 'SocialXE'를 선택한 경우 'SocialXE 버튼'이 표시됩니다. ※ '댓글 에디터 설정' 항목보다 사용자가 선택한 에디터가 우선합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( 'Textarea, 에디터(기본)', 'x2board' ),
            '2'       => esc_html__( "+ SocialXE 표시", 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'auto_view_sub'               => array(
        'id'      => 'auto_view_sub',
        'name'    => esc_html__( "*SocialXE 대댓글 자동 펼치기", 'x2board' ),
        'desc'    => esc_html__( "위의 '댓글창 방식 옵션'에서 'SocialXE'를 선택한 경우, '대댓글 자동 펼치기' 옵션 사용 여부를 결정합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '사용(기본)', 'x2board' ),
            'Y'       => esc_html__( "사용 안함", 'x2board' ),
        ),
    ),
    'sketchbook5_setup_header12'					=> array(
        'id'      => 'sketchbook5_setup_header12',
        'desc'    => esc_html__( "첨부파일", 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    'show_files'               => array(
        'id'      => 'show_files',
        'name'    => esc_html__( "첨부파일 표시 방법", 'x2board' ),
        'type'    => 'radio',
        'default' => '3',
        'options' => array(
            ' '      => esc_html__( '숨기고 버튼 표시', 'x2board' ),
            '2'       => esc_html__( "하단 표시", 'x2board' ),
            '3'       => esc_html__( "상단(제목 밑에) 표시(기본)", 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'files_type'               => array(
        'id'      => 'files_type',
        'name'    => esc_html__( "확장자 필터 기능", 'x2board' ),
        'desc'    => esc_html__( "첨부파일에서 이미지, 동영상, 음악 파일을 제외하는 기능을 사용합니다. 아래의 옵션에서 출력할 파일 타입을 선택하세요.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            'Y'       => esc_html__( "사용", 'x2board' ),
            ' '      => esc_html__( '사용 안함(기본)', 'x2board' ),
        ),
    ),
    'files_img'               => array(
        'id'      => 'files_img',
        'name'    => esc_html__( "이미지 파일", 'x2board' ),
        'desc'    => esc_html__( "첨부파일에서 이미지 파일(jpg, jpeg, gif, png)의 출력 여부를 선택합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '출력(기본)', 'x2board' ),
            'N'       => esc_html__( "출력 안함", 'x2board' ),
        ),
    ),
    'files_video'               => array(
        'id'      => 'files_video',
        'name'    => esc_html__( "동영상 파일", 'x2board' ),
        'desc'    => esc_html__( "첨부파일에서 동영상 파일(mpg, mpeg, avi, wmv, mp4, mov, mkv, swf, flv, ogv, webm)의 출력 여부를 선택합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '출력(기본)', 'x2board' ),
            'N'       => esc_html__( "출력 안함", 'x2board' ),
        ),
    ),
    'files_audio'               => array(
        'id'      => 'files_audio',
        'name'    => esc_html__( "음악 파일", 'x2board' ),
        'desc'    => esc_html__( "첨부파일에서 음악 파일(mp3, ogg, wma, wav, ape, flac, mid)의 출력 여부를 선택합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '출력(기본)', 'x2board' ),
            'N'       => esc_html__( "출력 안함", 'x2board' ),
        ),
    ),
    'files_etc'               => array(
        'id'      => 'files_etc',
        'name'    => esc_html__( "기타 파일", 'x2board' ),
        'desc'    => esc_html__( "위의 3가지 파일 타입(이미지, 비디오, 오디오)을 제외한 나머지 파일의 출력 여부를 선택합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '출력(기본)', 'x2board' ),
            'N'       => esc_html__( "출력 안함", 'x2board' ),
        ),
    ),
    'sketchbook5_setup_header13'					=> array(
        'id'      => 'sketchbook5_setup_header13',
        'desc'    => esc_html__( "본문 이미지 설정", 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    'img_opt'  => array(
        'id'      => 'img_opt',
        'name'    => esc_html__( '이미지 부가 기능', 'x2board' ),
        'desc'    => esc_html__( "1. 이미지 드래그 : 본문에 삽입된 이미지를 마우스로 드래그할 수 있습니다.", 'x2board' ),
        'type'    => 'multicheck',
        'options' => array(
            'drag'            => esc_html__( '이미지 드래그', 'x2board' ),
        ),
        // 'mandatory' => array(
        //     'PUBLIC'            => 'mandatory',
        // ),
    ),
    'img_insert'               => array(
        'id'      => 'img_insert',
        'name'    => esc_html__( "이미지 자동 출력", 'x2board' ),
        'desc'    => esc_html__( "첨부된 이미지를 본문에 자동 출력하는 기능입니다. *주의 : 본문에 에디터로 '삽입'하는 형식과는 달리 단순히 첨부된 이미지 파일을 보여주는 방법입니다. 추후 게시판 스킨을 다른 것으로 사용하거나 마이그레이션 하는 경우에 본문에 이미지가 표시되지 않으니 주의하세요.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            '2'      => esc_html__( '본문 상단', 'x2board' ),
            '3'       => esc_html__( "본문 하단", 'x2board' ),
            ' '       => esc_html__( "사용 안함(기본)", 'x2board' ),
        ),
    ),
    // 'img_insert2'               => array(
    //     'id'      => 'img_insert2',
    //     'name'    => esc_html__( "특정 이미지만 자동 출력", 'x2board' ),
    //     'desc'    => esc_html__( "첨부된 이미지 중에 파일 이름이 '_rd_gallery'로 끝나는 특정 이미지 파일만 자동 출력하는 기능입니다. 이 기능으로 특정 이미지만 자동 출력할 수 있습니다.", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         'Y'      => esc_html__( '사용', 'x2board' ),
    //         ' '       => esc_html__( "사용 안함(기본)", 'x2board' ),
    //     ),
    // ),
    'img_insert_align'               => array(
        'id'      => 'img_insert_align',
        'name'    => esc_html__( "자동 출력된 이미지 정렬", 'x2board' ),
        'desc'    => esc_html__( "자동 출력되는 이미지를 정렬합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            'Y'      => esc_html__( '가운데(기본)', 'x2board' ),
            'left'       => esc_html__( "좌측", 'x2board' ),
            'right'       => esc_html__( "우측", 'x2board' ),
        ),
    ),
    'img_insert_width'     => array(
        'id'      => 'img_insert_width',
        'name'    => esc_html__( '자동 출력된 이미지 넓이', 'x2board' ),
        'desc'    => esc_html__( "자동 출력되는 이미지의 넓이를 설정합니다. '단위(px 또는 %)'까지 입력하세요. 입력하지 않으면 제한하지 않습니다.", 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    'img_insert_height'     => array(
        'id'      => 'img_insert_height',
        'name'    => esc_html__( '자동 출력된 이미지 높이', 'x2board' ),
        'desc'    => esc_html__( "자동 출력되는 이미지의 높이를 설정합니다. '단위(px 또는 %)'까지 입력하세요. 입력하지 않으면 제한하지 않습니다.", 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    'img_insert_css'     => array(
        'id'      => 'img_insert_css',
        'name'    => esc_html__( '자동 출력된 갤러리 영역 CSS', 'x2board' ),
        'desc'    => esc_html__( '자동 출력되는 이미지를 감싸는 갤러리 영역의 스타일(CSS)을 직접 입력합니다.', 'x2board' ),
        'type'    => 'textarea',
        'options' => false,
    ),
    'img_insert_img_css'     => array(
        'id'      => 'img_insert_img_css',
        'name'    => esc_html__( '자동 출력된 이미지 CSS', 'x2board' ),
        'desc'    => esc_html__( '자동 출력되는 이미지의 스타일(CSS)을 직접 입력합니다.', 'x2board' ),
        'type'    => 'textarea',
        'options' => false,
    ),
    'sketchbook5_setup_header14'					=> array(
        'id'      => 'sketchbook5_setup_header14',
        'desc'    => esc_html__( "본문 일반 설정", 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    'rd_padding'     => array(
        'id'      => 'rd_padding',
        'name'    => esc_html__( '본문 전체 여백 설정', 'x2board' ),
        'desc'    => esc_html__( "본문의 전체 여백(padding)을 설정합니다. 사용자의 레이아웃에 따라 본문 폭이 달라 필요한 영역 확보를 하지 못하는 경우를 위해 옵션을 두었습니다. 일반 css 입력과 동일하므로 'px', 'em', '%' 등 '단위'까지 반드시(!) 입력해야 합니다(※ '0'으로 사용할 경우 '0'은 저장되지 않으니 '0px'을 입력하세요). 입력하지 않으면 기본설정은 '0 15px' 입니다. 예) '0px', '10px', '10px 20px 30px 10px', '3% 0' 등", 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    'rd_nav'               => array(
        'id'      => 'rd_nav',
        'name'    => esc_html__( "본문 상단 내비", 'x2board' ),
        'desc'    => esc_html__( "본문을 읽는 데 도움을 주는 기능('글자의 확대-축소', '상단-댓글-목록으로 이동', '프린트', '첨부파일', '이 게시물을', '수정', '삭제' 등)을 모은 내비게이션입니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '제목 영역 아래(기본)', 'x2board' ),
            '2'       => esc_html__( "제목 영역 위", 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'rd_nav_style'               => array(
        'id'      => 'rd_nav_style',
        'name'    => esc_html__( "본문 내비 스타일", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '테두리+박스(기본)', 'x2board' ),
            '2'       => esc_html__( "테두리 없음", 'x2board' ),
        ),
    ),
    'rd_nav_tx'               => array(
        'id'      => 'rd_nav_tx',
        'name'    => esc_html__( "본문 내비 텍스트 표시", 'x2board' ),
        'desc'    => esc_html__( "아이콘 옆에 텍스트를 표시합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            'Y'      => esc_html__( '텍스트 표시', 'x2board' ),
            ' '       => esc_html__( "텍스트 표시 안함(기본)", 'x2board' ),
        ),
    ),
    'rd_nav_side'               => array(
        'id'      => 'rd_nav_side',
        'name'    => esc_html__( "본문 사이드 내비", 'x2board' ),
        'desc'    => esc_html__( "처음에는 보이지 않다가 스크롤 하면 상단 내비가 윈도우 영역에서 사라지면 우측 하단에 나타나는 내비의 사용 여부를 결정합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '사용(기본)', 'x2board' ),
            'N'       => esc_html__( "사용 안함", 'x2board' ),
        ),
    ),
    'rd_nav_item'               => array(
        'id'      => 'rd_nav_item',
        'name'    => esc_html__( "본문 내비 프린트 버튼", 'x2board' ),
        'desc'    => esc_html__( "본문 내비의 프린트 버튼의 표시 여부를 설정합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '표시(기본)', 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'prev_next'               => array(
        'id'      => 'prev_next',
        'name'    => esc_html__( "이전글-다음글", 'x2board' ),
        'desc'    => esc_html__( "본문 하단의 링크, 키보드의 방향키 '←', '→' 을 사용하여 이전글, 다음글로 이동할 수 있습니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '본문 하단 텍스트 링크+단축키 사용(기본)', 'x2board' ),
            '2'       => esc_html__( "본문 내비 아이콘 버튼+단축키 사용", 'x2board' ),
            'N'       => esc_html__( "사용 안함", 'x2board' ),
        ),
    ),
    'prev_next_cut_size'     => array(
        'id'      => 'prev_next_cut_size',
        'name'    => esc_html__( '이전글-다음글 제목 글자수 제한', 'x2board' ),
        'desc'    => esc_html__( "이전글-다음글의 글자수를 제한합니다. 기본값은 '60' 입니다.", 'x2board' ),
        'type'    => 'text',
        'options' => false,
    ),
    'no_attached_img'					=> array(
        'id'      => 'no_attached_img',
        'name'    => esc_html__( '본문에 이미지가 없는 경우', 'x2board' ),
        'desc'    => esc_html__( "본문에 이미지가 없는 경우, 본문 상단에 미리 등록된 이미지를 표시합니다. 이 항목에서 이미지를 등록하시면 활성화됩니다.", 'x2board' ),
        'type'    => 'image',
        'options' => false,
    ),
    'et_var'               => array(
        'id'      => 'et_var',
        'name'    => esc_html__( "확장변수 위치", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '본문 안에(기본)', 'x2board' ),
            '2'       => esc_html__( "제목 아래", 'x2board' ),
        ),
    ),
    'display_sign'               => array(
        'id'      => 'display_sign',
        'name'    => esc_html__( "글쓴이 서명 표시", 'x2board' ),
        'type'    => 'radio',
        'default' => 'N',
        'options' => array(
            'Y'      => esc_html__( '표시', 'x2board' ),
            'N'       => esc_html__( "표시 안함(기본)", 'x2board' ),
        ),
    ),
    'votes'               => array(
        'id'      => 'votes',
        'name'    => esc_html__( "추천/비추천 표시", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '표시(기본)', 'x2board' ),
            '2'       => esc_html__( "추천만 표시", 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'declare'               => array(
        'id'      => 'declare',
        'name'    => esc_html__( "신고 표시", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '표시 안함(기본)', 'x2board' ),
            'Y'       => esc_html__( "표시", 'x2board' ),
        ),
    ),
    'to_sns'               => array(
        'id'      => 'to_sns',
        'name'    => esc_html__( "SNS로 보내기 버튼", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '작은 아이콘 + 하단 편집 영역(기본)', 'x2board' ),
            '2'       => esc_html__( "작은 아이콘 + 상단", 'x2board' ),
            '3'       => esc_html__( "큰 아이콘(본문 하단)", 'x2board' ),
            '4'       => esc_html__( "커스텀 입력(본문 하단)", 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'to_sns_small'               => array(
        'id'      => 'to_sns_small',
        'name'    => esc_html__( "SNS 작은 버튼 텍스트 표시", 'x2board' ),
        'desc'    => esc_html__( "위의 항목에서 '작은 아이콘' 사용 시에 아이콘 옆에 텍스트의 사용 여부를 설정합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '표시(기본)', 'x2board' ),
            'bubble'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    // 'to_sns_big'               => array(
    //     'id'      => 'to_sns_big',
    //     'name'    => esc_html__( "SNS 큰 버튼 정렬", 'x2board' ),
    //     'desc'    => esc_html__( "위의 항목에서 '큰 아이콘' 사용 시에 정렬을 설정합니다.", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '가운데(기본)', 'x2board' ),
    //         'left'       => esc_html__( "왼쪽", 'x2board' ),
    //         'right'       => esc_html__( "오른쪽", 'x2board' ),
    //     ),
    // ),
    'to_sns_content'     => array(
        'id'      => 'to_sns_content',
        'name'    => esc_html__( 'SNS 커스텀 버튼', 'x2board' ),
        'desc'    => esc_html__( "위의 항목에서 '커스텀 입력' 사용 시에 직접 코드를 입력할 수 있습니다. 예제 버튼은 매뉴얼 혹은 피드백 사이트를 참조하세요.", 'x2board' ),
        'type'    => 'textarea',
        'options' => false,
    ),
    'rd_ft_nav'  => array(
        'id'      => 'rd_ft_nav',
        'name'    => esc_html__( '본문 하단 메뉴 영역', 'x2board' ),
        'type'    => 'multicheck',
        'options' => array(
            'lst_btn'            => esc_html__( '목록 버튼 표시', 'x2board' ),
        ),
    ),
    'sketchbook5_setup_header15'					=> array(
        'id'      => 'sketchbook5_setup_header15',
        'desc'    => esc_html__( "피드백(트랙백, 댓글) 목록 설정", 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    'fdb_style'               => array(
        'id'      => 'fdb_style',
        'name'    => esc_html__( "댓글 스타일", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '테두리 없는(기본)', 'x2board' ),
            'fdb_v2'       => esc_html__( "테두리+네임택", 'x2board' ),
        ),
    ),
    'profile_img'               => array(
        'id'      => 'profile_img',
        'name'    => esc_html__( "프로필 이미지 표시", 'x2board' ),
        'desc'    => esc_html__( "댓글의 좌측, 방명록의 프로필 이미지를 보이게 할 것인지를 결정합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '표시(기본)', 'x2board' ),
            'no_profile'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    // 'fdb_hide'               => array(
    //     'id'      => 'fdb_hide',
    //     'name'    => esc_html__( "피드백 목록 최초 감추기", 'x2board' ),
    //     'desc'    => esc_html__( "처음에 댓글, 트랙백 목록이 숨겨져 있다가 'Comment' or 'Trackback' 버튼 클릭 시 펼쳐집니다.", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         'fdb_hide'      => esc_html__( '사용', 'x2board' ),
    //         ' '       => esc_html__( "사용 안함(기본)", 'x2board' ),
    //     ),
    // ),
    'cmt_wrt_position'               => array(
        'id'      => 'cmt_wrt_position',
        'name'    => esc_html__( "댓글 에디터 위치", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '댓글 목록 위(기본)', 'x2board' ),
            'cmt_wrt_btm'       => esc_html__( "댓글 목록 아래", 'x2board' ),
        ),
    ),
    'fdb_nav'               => array(
        'id'      => 'fdb_nav',
        'name'    => esc_html__( "댓글 편집창 위치", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '댓글 상단 + 숨기고 마우스 오버시 표시(기본)', 'x2board' ),
            'fdb_nav_btm'       => esc_html__( "댓글 하단 + 대댓글 버튼 표시", 'x2board' ),
        ),
    ),
    'cmt_this_btn'               => array(
        'id'      => 'cmt_this_btn',
        'name'    => esc_html__( "'이 댓글을' 표시", 'x2board' ),
        'desc'    => esc_html__( "기본으로 표시되는 '이 댓글을' 표시할 것인 지, 해당 목록에 포함되는 '추천, 비추천, 신고'를 직접 외부로 표시할 것인지를 결정합니다. 관리자에게는 '이 댓글을' 버튼이 항상 보입니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '표시(기본)', 'x2board' ),
            '2'       => esc_html__( "표시안함 + '추천, 비추천, 신고' 표시", 'x2board' ),
        ),
    ),
    'cmt_vote'               => array(
        'id'      => 'cmt_vote',
        'name'    => esc_html__( "댓글 추천-비추천 표시", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '추천-비추천이 있는 경우 표시(기본)', 'x2board' ),
            '2'       => esc_html__( "항상 표시", 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'cmt_vote_down'               => array(
        'id'      => 'cmt_vote_down',
        'name'    => esc_html__( "댓글 비추천 표시", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '표시(기본)', 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'sketchbook5_setup_header16'					=> array(
        'id'      => 'sketchbook5_setup_header16',
        'desc'    => esc_html__( "본문 제목 공통 설정", 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    'rd_style'               => array(
        'id'      => 'rd_style',
        'name'    => esc_html__( "프리셋", 'x2board' ),
        'desc'    => esc_html__( "'뷰어로 보기' 시에는 '블로그 스타일'로 표시됩니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '게시판 스타일(기본)', 'x2board' ),
            'blog'       => esc_html__( "블로그 스타일", 'x2board' ),
        ),
    ),
    'rd_css'     => array(
        'id'      => 'rd_css',
        'name'    => esc_html__( '전체 제목 영역 CSS', 'x2board' ),
        'desc'    => esc_html__( "제목를 둘러싸는 전체 영역의 스타일(CSS)을 직접 입력합니다.", 'x2board' ),
        'type'    => 'textarea',
        'options' => false,
    ),
    'rd_tl_font'               => array(
        'id'      => 'rd_tl_font',
        'name'    => esc_html__( "제목 글꼴", 'x2board' ),
        'desc'    => esc_html__( "'게시판 스타일'의 경우 '상단영역' 전체에 적용됩니다. *'나눔글꼴'을 사용하시는 경우에 가장 미려하게 보입니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '고딕체(기본)', 'x2board' ),
            'nmeb'       => esc_html__( "명조체", 'x2board' ),
            'np'       => esc_html__( "필기체", 'x2board' ),
        ),
    ),
    'rd_tl_css'     => array(
        'id'      => 'rd_tl_css',
        'name'    => esc_html__( '제목 CSS 입력', 'x2board' ),
        'desc'    => esc_html__( "제목의 스타일(CSS)을 직접 입력합니다.", 'x2board' ),
        'type'    => 'textarea',
        'options' => false,
    ),
    'sketchbook5_setup_header17'					=> array(
        'id'      => 'sketchbook5_setup_header17',
        'desc'    => esc_html__( "본문 '게시판 스타일' 제목 설정", 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    'rd_board_style'               => array(
        'id'      => 'rd_board_style',
        'name'    => esc_html__( "게시판 스타일 프리셋", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '기본 게시판(기본)', 'x2board' ),
            'xe_v3'       => esc_html__( "XE v3 스타일", 'x2board' ),
        ),
    ),
    'rd_cate'               => array(
        'id'      => 'rd_cate',
        'name'    => esc_html__( "카테고리", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '좌측 상단(기본)', 'x2board' ),
            '2'       => esc_html__( "좌측 하단", 'x2board' ),
            '3'       => esc_html__( "우측 하단", 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'rd_date'               => array(
        'id'      => 'rd_date',
        'name'    => esc_html__( "날짜", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '우측 상단(기본)', 'x2board' ),
            '2'       => esc_html__( "좌측 하단", 'x2board' ),
            '3'       => esc_html__( "우측 하단", 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'rd_nick'               => array(
        'id'      => 'rd_nick',
        'name'    => esc_html__( "글쓴이", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '좌측 하단(기본)', 'x2board' ),
            '2'       => esc_html__( "우측 상단", 'x2board' ),
            '3'       => esc_html__( "우측 하단", 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'rd_info'               => array(
        'id'      => 'rd_info',
        'name'    => esc_html__( "조회/추천/댓글 위치", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '우측 하단(기본)', 'x2board' ),
            '2'       => esc_html__( "좌측 하단", 'x2board' ),
        ),
    ),
    'rd_view'               => array(
        'id'      => 'rd_view',
        'name'    => esc_html__( "조회수", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '표시(기본)', 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'rd_vote'               => array(
        'id'      => 'rd_vote',
        'name'    => esc_html__( "추천수", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '표시(기본)', 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'rd_cmt'               => array(
        'id'      => 'rd_cmt',
        'name'    => esc_html__( "댓글수", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '표시(기본)', 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'rd_link'               => array(
        'id'      => 'rd_link',
        'name'    => esc_html__( "게시물 주소", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            '2'      => esc_html__( '좌측 하단', 'x2board' ),
            '3'       => esc_html__( "우측 하단", 'x2board' ),
            ' '       => esc_html__( "표시 안함(기본)", 'x2board' ),
        ),
    ),
    'rd_profile'               => array(
        'id'      => 'rd_profile',
        'name'    => esc_html__( "프로필 이미지 표시", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            'Y'      => esc_html__( '표시', 'x2board' ),
            ' '       => esc_html__( "표시 안함(기본)", 'x2board' ),
        ),
    ),
    // 'rd_hd_widget'     => array(
    //     'id'      => 'rd_hd_widget',
    //     'name'    => esc_html__( '제목 영역 위젯 등 출력', 'x2board' ),
    //     'desc'    => esc_html__( "제목 하단 영역에 나타나는 커스텀 공간입니다. 'html 입력' 또는 '회원정보위젯', '전광판위젯', '광고' 등을 넣어 사용할 수 있습니다.", 'x2board' ),
    //     'type'    => 'textarea',
    //     'options' => false,
    // ),
    'sketchbook5_setup_header18'					=> array(
        'id'      => 'sketchbook5_setup_header18',
        'desc'    => esc_html__( "본문 '블로그 스타일' 및 '뷰어로 보기' 제목 설정", 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    'rd_blog_style'               => array(
        'id'      => 'rd_blog_style',
        'name'    => esc_html__( "블로그 스타일 프리셋", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '굵은 라인 스타일(기본)', 'x2board' ),
            '2'       => esc_html__( "심플 라인 스타일", 'x2board' ),
            '3'       => esc_html__( "전체 회색 테두리 스타일", 'x2board' ),
            '4'       => esc_html__( "테두리 없는 스타일", 'x2board' ),
        ),
    ),
    'rd_h1_ani'               => array(
        'id'      => 'rd_h1_ani',
        'name'    => esc_html__( "제목 애니메이션", 'x2board' ),
        'desc'    => esc_html__( "*css3 animation을 지원하는 브라우저에서만 동작합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '페이드인(기본)', 'x2board' ),
            '2'       => esc_html__( "수직 한바퀴", 'x2board' ),
            'N'       => esc_html__( "없음", 'x2board' ),
        ),
    ),
    'rd_tl'               => array(
        'id'      => 'rd_tl',
        'name'    => esc_html__( "제목 표시 및 정렬", 'x2board' ),
        'desc'    => esc_html__( "*css3 animation을 지원하는 브라우저에서만 동작합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '좌측 정렬(기본)', 'x2board' ),
            'center'       => esc_html__( "가운데 정렬", 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'rd_top'               => array(
        'id'      => 'rd_top',
        'name'    => esc_html__( "상단 영역 정렬", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '제목 영역에 따라(기본)', 'x2board' ),
            'left'       => esc_html__( "좌측 정렬", 'x2board' ),
            'center'       => esc_html__( "가운데 정렬", 'x2board' ),
            'right'       => esc_html__( "우측 정렬", 'x2board' ),
        ),
    ),
    'rd_top_font'               => array(
        'id'      => 'rd_top_font',
        'name'    => esc_html__( "상단 영역 글꼴", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '고딕체(기본)', 'x2board' ),
            'nmeb'       => esc_html__( "명조체", 'x2board' ),
            'np'       => esc_html__( "필기체", 'x2board' ),
        ),
    ),
    // 'rd_btm'               => array(
    //     'id'      => 'rd_btm',
    //     'name'    => esc_html__( "하단 영역 정렬", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '제목 영역에 따라(기본)', 'x2board' ),
    //         'left'       => esc_html__( "좌측 정렬", 'x2board' ),
    //         'center'       => esc_html__( "가운데 정렬", 'x2board' ),
    //         'right'       => esc_html__( "우측 정렬", 'x2board' ),
    //     ),
    // ),
    'rd_btm_font'               => array(
        'id'      => 'rd_btm_font',
        'name'    => esc_html__( "하단 영역 글꼴", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '고딕체(기본)', 'x2board' ),
            'nmeb'       => esc_html__( "명조체", 'x2board' ),
            'np'       => esc_html__( "필기체", 'x2board' ),
        ),
    ),
    'rd_blog_cate'               => array(
        'id'      => 'rd_blog_cate',
        'name'    => esc_html__( "카테고리", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '상단(기본)', 'x2board' ),
            '2'       => esc_html__( "하단", 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'rd_blog_nick'               => array(
        'id'      => 'rd_blog_nick',
        'name'    => esc_html__( "글쓴이", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            '2'      => esc_html__( '상단', 'x2board' ),
            ' '       => esc_html__( "하단(기본)", 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'rd_blog_date'               => array(
        'id'      => 'rd_blog_date',
        'name'    => esc_html__( "날짜", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            '2'      => esc_html__( '상단', 'x2board' ),
            ' '       => esc_html__( "하단(기본)", 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'rd_blog_itm'                       => array(
        'id'      => 'rd_blog_itm',
        'name'    => esc_html__( '조회/추천/댓글 표시', 'x2board' ),
        // 'desc'    => esc_html__( 'Available post status', 'x2board' ),
        'type'    => 'multicheck',
        'options' => array(
            'view'            => esc_html__( '조회', 'x2board' ),
            'like'            => esc_html__( '추천', 'x2board' ),
            'cmt'            => esc_html__( '댓글', 'x2board' ),
        ),
        // 'mandatory' => array(
        //     'PUBLIC'            => 'mandatory',
        // ),
    ),
    'rd_preview'               => array(
        'id'      => 'rd_preview',
        'name'    => esc_html__( "본문 프리뷰", 'x2board' ),
        'desc'    => esc_html__( "'블로그 스타일'에서 제목 밑에 본문의 프리뷰 출력합니다. 확장변수에서 \"확장변수 이름 : 'rd_preview', 형식 : '여러 줄 입력칸(textarea)'\" 을 지정해주시면 사용할 수 있습니다. 자세한 설명은 XE자료실 또는 제작자의 홈페이지를 참조해주세요.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '사용(기본)', 'x2board' ),
            'N'       => esc_html__( "사용 안함", 'x2board' ),
        ),
    ),
    'sketchbook5_setup_header19'					=> array(
        'id'      => 'sketchbook5_setup_header19',
        'desc'    => esc_html__( "'뷰어로 보기' 설정", 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    'viewer_with'               => array(
        'id'      => 'viewer_with',
        'name'    => esc_html__( "게시판 상단 버튼", 'x2board' ),
        'desc'    => esc_html__( "게시판의 상단에 게시물을 클릭 시 바로 뷰어로 보게 하는 '게시물을 뷰어로 보기' 버튼의 표시 여부를 결정합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '표시(기본)', 'x2board' ),
            '2'       => esc_html__( "시작시 활성화", 'x2board' ),
            'N'       => esc_html__( "표시 안함", 'x2board' ),
        ),
    ),
    'viewer'               => array(
        'id'      => 'viewer',
        'name'    => esc_html__( "'뷰어로 보기' 버튼", 'x2board' ),
        'desc'    => esc_html__( "본문에서 '뷰어로 보기' 버튼을 설정합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '본문 우측 상단(기본)', 'x2board' ),
            '2'       => esc_html__( "본문 내비 영역에 아이콘 버튼", 'x2board' ),
            'N'       => esc_html__( "사용 안함", 'x2board' ),
        ),
    ),
    'lst_viewer'               => array(
        'id'      => 'lst_viewer',
        'name'    => esc_html__( "목록 게시물에 'viewer' 버튼", 'x2board' ),
        'desc'    => esc_html__( "목록의 게시물 링크에 마우스를 올릴 때 'viewer' 버튼을 나타낼 것인지를 결정합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '사용 안함(기본)', 'x2board' ),
            'Y'       => esc_html__( "사용", 'x2board' ),
        ),
    ),
    // 'viewer_style'               => array(
    //     'id'      => 'viewer_style',
    //     'name'    => esc_html__( "뷰어 스타일", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '검은색 배경(기본)', 'x2board' ),
    //         '2'       => esc_html__( "옅은 회색 배경", 'x2board' ),
    //     ),
    // ),
    // 'viewer_width'     => array(
    //     'id'      => 'viewer_width',
    //     'name'    => esc_html__( '뷰어 본문 넓이', 'x2board' ),
    //     'desc'    => esc_html__( "본문의 최대 넓이를 설정합니다. '숫자'만 입력하세요.(단위는 px입니다) 입력하지 않으면 '720' 입니다.", 'x2board' ),
    //     'type'    => 'text',
    //     'options' => false,
    // ),
    // 'viewer_lst'               => array(
    //     'id'      => 'viewer_lst',
    //     'name'    => esc_html__( "우측 목록 표시", 'x2board' ),
    //     'type'    => 'radio',
    //     'default' => ' ',
    //     'options' => array(
    //         ' '      => esc_html__( '표시(기본)', 'x2board' ),
    //         'N'       => esc_html__( "표시 안함", 'x2board' ),
    //     ),
    // ),
    'viewer_itm'                       => array(
        'id'      => 'viewer_itm',
        'name'    => esc_html__( '각 부분 표시 설정', 'x2board' ),
        'type'    => 'multicheck',
        'options' => array(
            'vote'            => esc_html__( '추천', 'x2board' ),
            'sns'            => esc_html__( 'SNS', 'x2board' ),
            'fnt'            => esc_html__( '파일, 트랙백', 'x2board' ),
            'cmt'            => esc_html__( '댓글', 'x2board' ),
        ),
        // 'mandatory' => array(
        //     'PUBLIC'            => 'mandatory',
        // ),
    ),
    'sketchbook5_setup_header20'					=> array(
        'id'      => 'sketchbook5_setup_header20',
        'desc'    => esc_html__( "*모바일 설정", 'x2board' ),
        'type'    => 'header',
        'options' => false,
    ),
    'img_link'               => array(
        'id'      => 'img_link',
        'name'    => esc_html__( "이미지 원본 링크", 'x2board' ),
        'desc'    => esc_html__( "모바일에서 이미지를 클릭하면 원본 링크로 이동합니다. *다른 리사이즈 애드온과 충돌이 될 수 있으니 해당 애드온 설정에서 모바일 설정을 확인해주세요.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( '사용', 'x2board' ),
            '2'       => esc_html__( "사용 안함(기본)", 'x2board' ),
        ),
    ),
    'm_editor'               => array(
        'id'      => 'm_editor',
        'name'    => esc_html__( "모바일 에디터", 'x2board' ),
        'desc'    => esc_html__( "모바일 에디터를 선택합니다.", 'x2board' ),
        'type'    => 'radio',
        'default' => ' ',
        'options' => array(
            ' '      => esc_html__( 'HTML5 WYSIWYG(기본)', 'x2board' ),
            '2'       => esc_html__( "Textarea", 'x2board' ),
            '3'       => esc_html__( "웹 에디터", 'x2board' ),
        ),
    ),
);
?>